language: csharp
solution: PolygonGeneralization.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore PolygonGeneralization.sln
  
script:    # the following commands are just examples, use whatever your build process requires
  - xbuild /p:Configuration=Debug PolygonGeneralization.sln
  - nunit-console PolygonGeneralization.Core.Tests/bin/Debug/PolygonGeneralization.Core.Tests.dll
  - nunit-console PolygonGeneralization.WinForms.Tests/bin/Debug/PolygonGeneralization.WinForms.Tests.dll